// [Co-developed with claude code -- Adam]
//
// Cross-language round trip: sFlow synthesised by the Python emitter, parsed by the C++ kernel.
//
// Phase 5 of doc/2026-07-27_p4_bmv2_support_plan.md replaces a missing sFlow agent with
// p4_proxy/proxy_agent/sflow_emitter.py, so bmv2 telemetry reaches the collector the kernel
// already listens on. That only works if the two agree byte for byte, and neither side's own
// tests can establish it: the Python tests compare against captured OVS bytes, which proves
// the layout matches OVS but not that this parser accepts it.
//
// So this test feeds the emitter's actual output to the actual parser and asserts the 5-tuple
// that comes out. If it passes, P4 telemetry works; if it fails, the twin would silently show
// nothing, which is the failure mode this whole phase exists to remove.
//
// The fixtures are generated by p4_proxy/tests/generate_emitted_fixtures.py and committed, so
// the C++ suite needs no Python at build time. test_sflow_emitter.py fails if the emitter
// drifts from the committed bytes, so a forgotten regeneration cannot leave this test
// validating a stale layout.

#include <gtest/gtest.h>

#include "common_types/SFlowType.hpp"
#include "event_system/EventBus.hpp"
#include "ndt_core/collection/Classifier.hpp"
#include "ndt_core/collection/FlowLinkUsageCollector.hpp"
#include "ndt_core/collection/TopologyAndFlowMonitor.hpp"
#include "utils/Logger.hpp"
#include "utils/Utils.hpp"

#include <arpa/inet.h>
#include <atomic>
#include <thread>
#include <filesystem>
#include <fstream>
#include <memory>
#include <optional>
#include <shared_mutex>
#include <string>
#include <vector>

namespace
{

class ProbeCollector : public sflow::FlowLinkUsageCollector
{
  public:
    ProbeCollector(std::shared_ptr<TopologyAndFlowMonitor> monitor,
                   std::shared_ptr<EventBus> bus,
                   std::shared_ptr<ndtClassifier::Classifier> classifier)
        : sflow::FlowLinkUsageCollector(std::move(monitor),
                                        nullptr,
                                        std::move(bus),
                                        utils::DeploymentMode::MININET,
                                        std::move(classifier))
    {
    }

    using sflow::FlowLinkUsageCollector::handlePacket;
    using sflow::FlowLinkUsageCollector::malformedDatagramCount;
    using sflow::FlowLinkUsageCollector::lookupOfport;
    using sflow::FlowLinkUsageCollector::usesIdentityPortMapping;
    using sflow::FlowLinkUsageCollector::sampledByteCreditFor;
};

std::filesystem::path fixtureDir()
{
    for (const auto* candidate :
         {"tests/fixtures", "../tests/fixtures", "../../tests/fixtures"})
    {
        if (std::filesystem::is_directory(candidate))
        {
            return candidate;
        }
    }
    return {};
}

std::vector<char> loadFixture(const std::string& name)
{
    const auto dir = fixtureDir();
    if (dir.empty())
    {
        return {};
    }
    std::ifstream f(dir / name, std::ios::binary);
    if (!f)
    {
        return {};
    }
    return {std::istreambuf_iterator<char>(f), std::istreambuf_iterator<char>()};
}

class EmitterRoundtripTest : public ::testing::Test
{
  protected:
    static void SetUpTestSuite()
    {
        LogConfig cfg;
        cfg.level = spdlog::level::off;
        Logger::init(cfg);
    }

    void SetUp() override
    {
        auto bus = std::make_shared<EventBus>();
        auto monitor = std::make_shared<TopologyAndFlowMonitor>(
            std::make_shared<Graph>(),
            std::make_shared<std::shared_mutex>(),
            bus,
            utils::DeploymentMode::MININET);
        m_collector = std::make_unique<ProbeCollector>(
            monitor, bus, std::make_shared<ndtClassifier::Classifier>());
    }

    /// Feeds one emitted fixture, skipping the test if it has not been generated.
    void feed(const std::string& name)
    {
        auto data = loadFixture(name);
        ASSERT_FALSE(data.empty())
            << name << " missing. Generate it with:\n"
            << "  python3 p4_proxy/tests/generate_emitted_fixtures.py";
        m_collector->handlePacket(data.data(), data.size());
    }

    /// Finds a flow by protocol, so assertions can name what they expect.
    std::optional<sflow::FlowKey> findFlowWithProtocol(uint8_t protocol) const
    {
        for (const auto& [key, info] : m_collector->getFlowInfoTable())
        {
            if (key.protocol == protocol)
            {
                return key;
            }
        }
        return std::nullopt;
    }

    std::unique_ptr<ProbeCollector> m_collector;
};

} // namespace

TEST_F(EmitterRoundtripTest, ParsesEmittedTcpSampleIntoTheExactFiveTuple)
{
    // The headline assertion of Phase 5. generate_emitted_fixtures.py builds this frame as
    // 10.0.0.1:5001 -> 10.0.0.4:40997 over TCP; every one of those values has to survive the
    // emitter's framing and the parser's fixed offsets.
    feed("emitted_tcp.bin");

    EXPECT_EQ(m_collector->malformedDatagramCount(), 0u)
        << "the parser rejected the emitter's output as malformed";

    const auto flow = findFlowWithProtocol(6);
    ASSERT_TRUE(flow.has_value()) << "no TCP flow recovered from the emitted datagram";

    EXPECT_EQ(utils::ipToString(flow->srcIP), "10.0.0.1");
    EXPECT_EQ(utils::ipToString(flow->dstIP), "10.0.0.4");
    EXPECT_EQ(flow->srcPort, 5001);
    EXPECT_EQ(flow->dstPort, 40997);
    EXPECT_EQ(int(flow->protocol), 6);
}

TEST_F(EmitterRoundtripTest, ParsesEmittedUdpSample)
{
    feed("emitted_udp.bin");

    const auto flow = findFlowWithProtocol(17);
    ASSERT_TRUE(flow.has_value()) << "no UDP flow recovered";

    EXPECT_EQ(utils::ipToString(flow->srcIP), "10.0.0.2");
    EXPECT_EQ(utils::ipToString(flow->dstIP), "10.0.0.3");
    EXPECT_EQ(flow->srcPort, 5201);
    EXPECT_EQ(flow->dstPort, 33333);
}

TEST_F(EmitterRoundtripTest, ParsesEmittedIcmpSampleWithTypeAndCodeInThePortFields)
{
    // The kernel carries ICMP type and code in the *port* fields of the FlowKey rather than in
    // its icmpType/icmpCode members -- see FlowLinkUsageCollector.cpp, where the key is built
    // as {srcIp, dstIp, icmpType, icmpCode, protocol}, and doc/2026-01-02_ndt_api.md, which documents
    // src_port as the type and dst_port as the code. The P4 pipeline mirrors that by lifting
    // ICMP type/code into the same l4 port metadata the ternary table keys on, so the two
    // representations agree.
    //
    // The fixture is an echo request: type 8, code 0.
    feed("emitted_icmp.bin");

    const auto flow = findFlowWithProtocol(1);
    ASSERT_TRUE(flow.has_value()) << "no ICMP flow recovered";

    EXPECT_EQ(utils::ipToString(flow->srcIP), "10.0.0.1");
    EXPECT_EQ(utils::ipToString(flow->dstIP), "10.0.0.2");
    EXPECT_EQ(flow->srcPort, 8) << "ICMP type belongs in the src_port field";
    EXPECT_EQ(flow->dstPort, 0) << "ICMP code belongs in the dst_port field";
}

TEST_F(EmitterRoundtripTest, ParsesIcmpWithBothTypeAndCodeNonZero)
{
    // Echo request has code 0, which is also the default-initialised value, so it cannot
    // distinguish "parsed correctly" from "never populated". Destination-unreachable
    // (type 3, code 1) makes both fields non-zero.
    feed("emitted_icmp_unreachable.bin");

    const auto flow = findFlowWithProtocol(1);
    ASSERT_TRUE(flow.has_value()) << "no ICMP flow recovered";

    EXPECT_EQ(utils::ipToString(flow->srcIP), "10.0.0.3");
    EXPECT_EQ(utils::ipToString(flow->dstIP), "10.0.0.4");
    EXPECT_EQ(flow->srcPort, 3) << "ICMP type 3 (destination unreachable)";
    EXPECT_EQ(flow->dstPort, 1) << "ICMP code 1 (host unreachable)";
}

TEST_F(EmitterRoundtripTest, IgnoresEmittedArpWithoutInventingAFlow)
{
    // ARP is not IPv4, so it must be skipped. An off-by-one in the record arithmetic would show
    // up here as a flow with a nonsense protocol rather than as an error.
    feed("emitted_arp.bin");

    EXPECT_EQ(m_collector->getFlowInfoTable().size(), 0u)
        << "a non-IPv4 frame was parsed into a flow";
    EXPECT_EQ(m_collector->malformedDatagramCount(), 0u)
        << "a well-formed datagram carrying ARP should not count as malformed";
}

TEST_F(EmitterRoundtripTest, ParsesATruncatedFrameAndReportsTheOriginalLength)
{
    // The emitter truncates the captured header to 128 bytes but reports the original frame
    // length, which is what the kernel's rate arithmetic multiplies by the sampling rate. If
    // truncation broke the 5-tuple, or the length were the truncated one, rates would be wrong
    // rather than absent -- a much harder failure to notice.
    feed("emitted_tcp_truncated.bin");

    const auto flow = findFlowWithProtocol(6);
    ASSERT_TRUE(flow.has_value()) << "no flow recovered from a truncated frame";

    EXPECT_EQ(utils::ipToString(flow->srcIP), "10.0.0.1");
    EXPECT_EQ(flow->srcPort, 5001);
    EXPECT_EQ(flow->dstPort, 40998);
}

TEST_F(EmitterRoundtripTest, WalksEverySampleInAMultiSampleDatagram)
{
    // OVS batches several samples per datagram and the emitter can too, so the parser has to
    // chain through them by length. Getting that wrong typically yields the first sample only.
    feed("emitted_multi.bin");

    const auto table = m_collector->getFlowInfoTable();
    EXPECT_EQ(table.size(), 3u)
        << "expected one flow per sample (TCP, UDP, ICMP) from the batched datagram";

    EXPECT_TRUE(findFlowWithProtocol(6).has_value()) << "TCP sample not parsed";
    EXPECT_TRUE(findFlowWithProtocol(17).has_value()) << "UDP sample not parsed";
    EXPECT_TRUE(findFlowWithProtocol(1).has_value()) << "ICMP sample not parsed";
    EXPECT_EQ(m_collector->malformedDatagramCount(), 0u);
}

TEST_F(EmitterRoundtripTest, BatchedSamplesBankEverySampleBytes)
{
    // WalksEverySampleInAMultiSampleDatagram above proves the parser *chains* through all three
    // samples: three protocols go in, three flows come out. That is not the same property as
    // banking all three samples' bytes, and only the second one decides what the twin reports.
    //
    // Nothing observable separates them. A parser that walked every sample but credited the
    // byte counter once would still leave three flows in the flow table, still count zero
    // malformed datagrams, and still pass every existing assertion -- while understating every
    // link rate by 3x, silently and uniformly. That is the same shape as the clone-replica
    // stacking bug, which also produced a uniformly wrong rate that absolute numbers alone
    // could not distinguish from a busier fabric.
    //
    // This matters now rather than in the abstract: the emitter sends one sample per datagram
    // today, so the batching path has never carried production traffic. Turning batching on to
    // cut datagram count would make this arithmetic load-bearing overnight.
    //
    // The expected values are derived from the single-sample fixtures rather than written down,
    // so the test cannot drift out of step with the frames the generator happens to build. In
    // emitted_multi.bin the TCP and ICMP samples arrive on ingress port 1 and the UDP sample on
    // port 3, so port 1 must bank the sum of two and port 3 the third.
    // Network byte order, deliberately not converted: the parser stores the agent address as
    // `uint32_t agentIp = data[2]` straight off the wire (FlowLinkUsageCollector.cpp:960) with
    // no ntohl, and keys m_counterReports on that value. Passing host order here finds nothing
    // and the counter reads 0 -- which is why the guards below assert the single-sample credit
    // is non-zero before comparing anything. Without them this test would have "passed" by
    // comparing 0 == 0 + 0.
    const uint32_t agentIp = ::inet_addr("192.168.123.11");

    // Every sample lands on port 0 in this harness, and that is correct rather than a
    // limitation to work around. In MININET mode the parser rewrites both ports through
    // lookupOfport() before keying the counter; usesIdentityPortMapping() returns false when no
    // topology is loaded (it refuses to guess bmv2 semantics for what might be an OVS run), so
    // the empty ifIndex map maps every ifIndex to 0. relevantPort is therefore 0 for all three
    // samples.
    //
    // The property under test is arithmetic -- was every sample's bytes banked -- not
    // attribution, which is what the per-edge reconciliation harness covers. Collapsing to one
    // key actually sharpens it: the batch must equal the sum of the three singles, and a parser
    // that credited only the first sample would return exactly the TCP figure.
    auto creditFrom = [&](const std::string& fixture, uint32_t port) -> uint64_t {
        auto bus = std::make_shared<EventBus>();
        auto monitor = std::make_shared<TopologyAndFlowMonitor>(
            std::make_shared<Graph>(),
            std::make_shared<std::shared_mutex>(),
            bus,
            utils::DeploymentMode::MININET);
        ProbeCollector fresh(monitor, bus, std::make_shared<ndtClassifier::Classifier>());
        auto bytes = loadFixture(fixture);
        EXPECT_FALSE(bytes.empty()) << "fixture missing: " << fixture;
        fresh.handlePacket(bytes.data(), bytes.size());
        return fresh.sampledByteCreditFor(agentIp, port);
    };

    constexpr uint32_t PORT = 0;
    const uint64_t tcpAlone = creditFrom("emitted_tcp.bin", PORT);
    const uint64_t udpAlone = creditFrom("emitted_udp.bin", PORT);
    const uint64_t icmpAlone = creditFrom("emitted_icmp.bin", PORT);

    // Without these the test would compare 0 == 0 + 0 + 0 and pass while measuring nothing.
    // They already earned their place: the first draft keyed the counter on the host-order
    // agent address and every figure came back 0.
    ASSERT_GT(tcpAlone, 0u) << "single-sample TCP banked nothing; the key or the mode is wrong";
    ASSERT_GT(udpAlone, 0u);
    ASSERT_GT(icmpAlone, 0u);

    const uint64_t batched = creditFrom("emitted_multi.bin", PORT);

    EXPECT_EQ(batched, tcpAlone + udpAlone + icmpAlone)
        << "a three-sample datagram banked " << batched << " but its samples are worth "
        << tcpAlone << " + " << udpAlone << " + " << icmpAlone << " = "
        << (tcpAlone + udpAlone + icmpAlone)
        << ". Equal to the TCP figure alone would mean only the first sample was credited";
}

TEST_F(EmitterRoundtripTest, EmittedAndCapturedDatagramsAgreeOnStructure)
{
    // Both sources parse without complaint, which is the property that lets the kernel treat
    // P4 and OVS telemetry identically -- the point of synthesising sFlow rather than adding a
    // second ingest path.
    feed("emitted_tcp.bin");
    const size_t fromEmitted = m_collector->getFlowInfoTable().size();
    ASSERT_GT(fromEmitted, 0u);

    // Reuse the same collector: a real one receives from every switch, and mixing sources must
    // not corrupt either.
    auto captured = loadFixture("tcp_00.bin");
    ASSERT_FALSE(captured.empty());
    m_collector->handlePacket(captured.data(), captured.size());

    EXPECT_GE(m_collector->getFlowInfoTable().size(), fromEmitted)
        << "feeding a captured OVS datagram after an emitted one lost flows";
    EXPECT_EQ(m_collector->malformedDatagramCount(), 0u)
        << "mixing emitted and captured datagrams produced a parse failure";
}

// ---------------------------------------------------------------------------------------------
// ifIndex -> port mapping selection
//
// Under bmv2 there is no ovs-vsctl to ask, so the collector must treat the emitter's ifIndex as
// the port directly. Getting this wrong is invisible at runtime: every port resolves to 0, and
// link usage and flow paths come out empty rather than wrong, with no error anywhere.
// ---------------------------------------------------------------------------------------------

TEST(IdentityPortMappingTest, AnAllBmv2TopologySkipsOvsVsctl)
{
    const std::map<SwitchKind, std::vector<uint64_t>> groups{{SwitchKind::BMV2, {1, 2, 3}}};
    EXPECT_TRUE(ProbeCollector::usesIdentityPortMapping(groups));
}

TEST(IdentityPortMappingTest, AnAllOvsTopologyStillTranslates)
{
    const std::map<SwitchKind, std::vector<uint64_t>> groups{{SwitchKind::OVS, {1, 2}}};
    EXPECT_FALSE(ProbeCollector::usesIdentityPortMapping(groups))
        << "OVS reports kernel interface indices, which are not port numbers";
}

TEST(IdentityPortMappingTest, AnEmptyTopologyKeepsTheExistingBehaviour)
{
    // The collector can start before the topology is loaded. Guessing bmv2 here would break
    // every OVS deployment, so absence of information must not change behaviour.
    EXPECT_FALSE(ProbeCollector::usesIdentityPortMapping({}));
}

TEST(IdentityPortMappingTest, AMixedTopologyDoesNotUseIdentity)
{
    // Homogeneity validation normally rejects this, but ALLOW_MIXED_DATAPLANE can permit it.
    // A single map cannot be both, so the safe choice is the translating one: it is wrong only
    // for the bmv2 switches, whereas identity would be wrong for the OVS ones as well.
    const std::map<SwitchKind, std::vector<uint64_t>> groups{
        {SwitchKind::OVS, {1}}, {SwitchKind::BMV2, {2}}};
    EXPECT_FALSE(ProbeCollector::usesIdentityPortMapping(groups));
}

TEST(IdentityPortMappingTest, HardwareSwitchesTranslate)
{
    const std::map<SwitchKind, std::vector<uint64_t>> groups{{SwitchKind::HARDWARE, {1}}};
    EXPECT_FALSE(ProbeCollector::usesIdentityPortMapping(groups));
}

// ---------------------------------------------------------------------------------------------
// When the mapping is decided
//
// The unit tests above pin the decision *function*. They passed while the feature was dead:
// the collector was deciding in start(), before the monitor's thread had loaded the topology,
// so it always saw zero switches and always took the ovs-vsctl branch. Measured from a real
// run -- "Populating ifIndex to OFPort map..." at .283, "Data plane: bmv2" at .286, and the
// identity log line never appeared at all.
//
// So these tests drive lookupOfport, which is where the decision now happens, with the
// topology arriving late exactly as it does in production.
// ---------------------------------------------------------------------------------------------

namespace
{

/// Exposes the topology load, which is protected. Tests need it because getSwitchKindGroups
/// reads a cache only this function fills.
class ProbeMonitor : public TopologyAndFlowMonitor
{
  public:
    using TopologyAndFlowMonitor::TopologyAndFlowMonitor;
    using TopologyAndFlowMonitor::loadStaticTopologyFromFile;
};

/// A collector whose monitor starts empty, so the topology can be made to arrive afterwards.
///
/// Goes through the real loadStaticTopologyFromFile rather than adding vertices directly:
/// getSwitchKindGroups reads m_dpidToSwitchKind, which only that function populates. An earlier
/// version of this fixture poked the graph and so tested nothing.
class LateTopologyFixture : public ::testing::Test
{
  protected:
    static void SetUpTestSuite()
    {
        LogConfig cfg;
        cfg.level = spdlog::level::off;
        Logger::init(cfg);
    }

    void SetUp() override
    {
        auto graph = std::make_shared<Graph>();
        auto mutex = std::make_shared<std::shared_mutex>();
        auto bus = std::make_shared<EventBus>();
        m_monitor = std::make_shared<ProbeMonitor>(
            graph, mutex, bus, utils::DeploymentMode::MININET);
        m_collector = std::make_unique<ProbeCollector>(
            m_monitor, bus, std::make_shared<ndtClassifier::Classifier>());
    }

    void TearDown() override
    {
        for (const auto& path : m_tempFiles)
        {
            std::filesystem::remove(path);
        }
    }

    /// Loads a topology of switches of the given kinds, as the monitor's thread would.
    void loadTopology(const std::vector<std::pair<uint64_t, std::string>>& switches)
    {
        nlohmann::json nodes = nlohmann::json::array();
        for (const auto& [dpid, brand] : switches)
        {
            // Every field the loader reads; it uses at() rather than value(), so an omission
            // throws rather than defaulting.
            nodes.push_back({{"device_name", "s" + std::to_string(dpid)},
                             {"bridge_name", "s" + std::to_string(dpid)},
                             {"nickname", "s" + std::to_string(dpid)},
                             {"brand_name", brand},
                             {"device_layer", 2},
                             {"dpid", dpid},
                             {"ip", nlohmann::json::array({"192.168.123.11"})},
                             {"mac", 0},
                             {"smart_plug_ip", ""},
                             {"smart_plug_outlet", 0},
                             {"vertex_type", 0},
                             {"ecmp_groups", nlohmann::json::array()}});
        }
        const nlohmann::json topology{{"nodes", nodes},
                                      {"edges", nlohmann::json::array()},
                                      {"links", nlohmann::json::array()}};

        const auto path = std::filesystem::temp_directory_path() /
                          ("ndt_late_topo_" + std::to_string(++m_counter) + ".json");
        std::ofstream(path) << topology.dump();
        m_tempFiles.push_back(path);

        m_monitor->loadStaticTopologyFromFile(path.string());
    }

    std::shared_ptr<ProbeMonitor> m_monitor;
    std::unique_ptr<ProbeCollector> m_collector;
    std::vector<std::filesystem::path> m_tempFiles;
    static int m_counter;
};

int LateTopologyFixture::m_counter = 0;

} // namespace

TEST_F(LateTopologyFixture, IdentityMappingIsChosenEvenWhenTheTopologyLoadsAfterStartup)
{
    // The regression. The collector is constructed against an empty topology, which then
    // becomes all-bmv2 before any sample arrives -- the real startup order.
    loadTopology({{1, "BMv2"}, {2, "BMv2"}});

    EXPECT_EQ(m_collector->lookupOfport(3), 3u)
        << "identity mapping was not applied; deciding too early is what caused this";
    EXPECT_EQ(m_collector->lookupOfport(7), 7u);
}

TEST_F(LateTopologyFixture, TheDecisionIsMadeOnceAndSticks)
{
    // std::call_once, so a topology that changes later cannot flip the mapping mid-run and
    // start reinterpreting ports differently for samples already in flight.
    loadTopology({{1, "BMv2"}});
    EXPECT_EQ(m_collector->lookupOfport(5), 5u);

    loadTopology({{1, "OVS"}});
    EXPECT_EQ(m_collector->lookupOfport(5), 5u) << "the mapping changed after the first lookup";
}

TEST_F(LateTopologyFixture, AnOvsTopologyStillGoesThroughTheMap)
{
    // No ovs-vsctl in a test environment, so the map is empty and every port resolves to 0.
    // That is the pre-existing OVS behaviour and must be preserved: what matters here is that
    // it did *not* take the identity branch and return the ifIndex unchanged.
    loadTopology({{1, "OVS"}});
    EXPECT_EQ(m_collector->lookupOfport(3), 0u)
        << "an OVS topology must not use identity mapping";
}

TEST_F(LateTopologyFixture, ConcurrentFirstLookupsAgreeOnOneDecision)
{
    // lookupOfport runs on every sFlow worker thread, and the first call is what decides.
    loadTopology({{1, "BMv2"}});

    constexpr int kThreads = 8;
    std::vector<std::thread> threads;
    std::atomic<int> wrong{0};
    for (int i = 0; i < kThreads; ++i)
    {
        threads.emplace_back([this, &wrong] {
            for (uint32_t port = 1; port <= 50; ++port)
            {
                if (m_collector->lookupOfport(port) != port)
                {
                    wrong.fetch_add(1);
                }
            }
        });
    }
    for (auto& t : threads)
    {
        t.join();
    }
    EXPECT_EQ(wrong.load(), 0) << "concurrent first lookups disagreed on the mapping";
}
