#!/usr/bin/env bash
#
# L0: does every component still build?
#
# Runs in seconds-to-minutes, needs no Mininet and no running kernel, and catches the
# most common cross-repo breakage: changing a shared header in the kernel and only
# noticing that Energy-Saving-App no longer compiles a week later.
#
# Each component reports one of:
#   PASS     built cleanly
#   FAIL     build error -- exit code will be non-zero
#   SKIP     toolchain absent on this machine (not a failure; reported so you know
#            coverage was reduced)
#
# Usage:
#   ./l0_build_check.sh                  # everything
#   ./l0_build_check.sh kernel p4        # only the named components
#   ./l0_build_check.sh --list
#
# [Co-developed with claude code -- Adam]

set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=components.env
source "$HERE/components.env"

if [[ -t 1 && -z "${NO_COLOR:-}" ]]; then
    R=$'\033[31m'; G=$'\033[32m'; Y=$'\033[33m'; D=$'\033[2m'; N=$'\033[0m'
else
    R=''; G=''; Y=''; D=''; N=''
fi

mkdir -p "$LOG_DIR"

PASSED=(); FAILED=(); SKIPPED=()

# run_build <name> <log-name> <command...>
# The build output goes to a log so this script's own output stays scannable; on failure
# the last 25 lines are shown inline, which is almost always where the error is.
run_build() {
    local name="$1" logname="$2"; shift 2
    local log="$LOG_DIR/build_${logname}.log"
    printf '  %-28s ' "$name"
    if "$@" >"$log" 2>&1; then
        echo "${G}PASS${N}  ${D}($log)${N}"
        PASSED+=("$name")
    else
        echo "${R}FAIL${N}  ${D}($log)${N}"
        FAILED+=("$name")
        echo "${D}    --- last 25 lines ---${N}"
        tail -25 "$log" | sed 's/^/    /'
        echo "${D}    ---------------------${N}"
    fi
}

skip() {
    printf '  %-28s %s\n' "$1" "${Y}SKIP${N}  ${D}$2${N}"
    SKIPPED+=("$1: $2")
}

have() { command -v "$1" >/dev/null 2>&1; }

# --- individual component builds -------------------------------------------------

build_kernel() {
    # -Werror is on, so any new warning is already a build failure here.
    have cmake || { skip "NDTwin-Kernel" "cmake not installed"; return; }
    if [[ ! -f "$KERNEL_DIR/setting/AppConfig.hpp" ]]; then
        # Generated by CMake from AppConfig.hpp.example; a fresh clone has neither.
        echo "  ${D}note: setting/AppConfig.hpp absent; CMake will generate it${N}"
    fi
    run_build "NDTwin-Kernel" kernel \
        bash -c "cmake -S '$KERNEL_DIR' -B '$KERNEL_DIR/build' -DCMAKE_BUILD_TYPE=Debug \
                 && cmake --build '$KERNEL_DIR/build' -j\$(nproc)"
}

build_p4() {
    have p4c-bm2-ss || { skip "P4 pipeline" "p4c-bm2-ss not installed"; return; }
    mkdir -p "$P4_BUILD_DIR"
    run_build "P4 pipeline" p4 \
        p4c-bm2-ss --arch v1model \
            -o "$P4_BUILD_DIR/ndtwin_switch.json" \
            --p4runtime-files "$P4_BUILD_DIR/ndtwin_switch.p4info.txt" \
            "$P4_SRC"
}

build_energy_app() {
    have g++ || { skip "Energy-Saving-App" "g++ not installed"; return; }
    # Its Makefile bootstraps include/app/settings.hpp from .example, so a fresh clone
    # builds. `sim` also copies the binary into Simulation-Platform-Manager.
    run_build "Energy-Saving-App" energy_app make -C "$ENERGY_APP_DIR" all
}

build_sim_mgr() {
    have g++ || { skip "Simulation-Platform-Manager" "g++ not installed"; return; }
    run_build "Simulation-Platform-Manager" sim_mgr make -C "$SIM_MGR_DIR" all
}

build_visualizer() {
    [[ -x "$VISUALIZER_DIR/mvnw" ]] || { skip "Network-Traffic-Visualizer" "mvnw missing"; return; }
    have java || { skip "Network-Traffic-Visualizer" "java not installed"; return; }
    run_build "Network-Traffic-Visualizer" visualizer \
        bash -c "cd '$VISUALIZER_DIR' && ./mvnw -q -B compile"
}

build_webgui() {
    # No node/pnpm on this machine; the supported path is Docker, and a build there is
    # slow enough that we only validate the compose file unless asked for the full build.
    if have pnpm; then
        run_build "Web-GUI" webgui \
            bash -c "cd '$WEBGUI_DIR' && pnpm install --frozen-lockfile && pnpm build"
    elif have docker && docker info >/dev/null 2>&1; then
        if [[ "${L0_WEBGUI_DOCKER_BUILD:-0}" == "1" ]]; then
            run_build "Web-GUI (docker build)" webgui \
                docker compose -f "$WEBGUI_DIR/docker-compose.yml" build
        else
            run_build "Web-GUI (compose validate)" webgui \
                docker compose -f "$WEBGUI_DIR/docker-compose.yml" config
            echo "  ${D}note: set L0_WEBGUI_DOCKER_BUILD=1 for a full image build${N}"
        fi
    else
        skip "Web-GUI" "neither pnpm nor a usable docker daemon"
    fi
}

build_python_components() {
    # Syntax check only -- these are scripts with heavy runtime dependencies (Mininet,
    # nornir, a live kernel), so importing them here is not viable.
    #
    # ast.parse rather than py_compile: py_compile writes bytecode next to the source,
    # and these trees contain root-owned __pycache__ directories left by sudo Mininet
    # runs, which makes the check fail for reasons unrelated to the code. Parsing gives
    # identical coverage (both only catch SyntaxError) and writes nothing.
    local checker='import ast,sys
for f in sys.argv[1:]:
    with open(f, encoding="utf-8") as fh:
        ast.parse(fh.read(), filename=f)
print("syntax ok:", " ".join(sys.argv[1:]))'

    local specs=(
        "Network-State-Recorder|$NSR_PY_BIN|$NSR_DIR|network_state_recorder.py"
        "Network-Traffic-Generator|$NTG_PY_BIN|$NTG_DIR|network_traffic_generator.py network_traffic_generator_worker_node.py"
        "Traffic-Engineering-App|$TE_PY_BIN|$TE_APP_DIR|Traffic-engineering-App.py"
    )
    local spec name py dir files
    for spec in "${specs[@]}"; do
        IFS='|' read -r name py dir files <<<"$spec"
        if [[ ! -x "$py" ]]; then
            skip "$name" "interpreter not found: $py"
            continue
        fi
        # shellcheck disable=SC2086
        run_build "$name" "$(echo "$name" | tr 'A-Z-' 'a-z_')" \
            bash -c "cd '$dir' && '$py' -c '$checker' $files"
    done
}

build_contract_tools() {
    have python3 || { skip "contract test tooling" "python3 not installed"; return; }
    run_build "contract test tooling" contract_tools \
        bash -c "cd '$CONTRACT_DIR' && python3 run_contract_test.py --self-test"
}

# Interpreters for the python components, resolved once.
NSR_PY_BIN="$NTG_PY"     # NSR runs under ntg-env per its start script
NTG_PY_BIN="$NTG_PY"
TE_PY_BIN="$TE_PY"

declare -A TARGETS=(
    [kernel]=build_kernel
    [p4]=build_p4
    [energy]=build_energy_app
    [sim]=build_sim_mgr
    [visualizer]=build_visualizer
    [webgui]=build_webgui
    [python]=build_python_components
    [contract]=build_contract_tools
)
ORDER=(kernel p4 energy sim visualizer webgui python contract)

if [[ "${1:-}" == "--list" ]]; then
    printf 'available targets: %s\n' "${ORDER[*]}"
    exit 0
fi

SELECTED=("${ORDER[@]}")
if [[ $# -gt 0 ]]; then
    SELECTED=()
    for arg in "$@"; do
        if [[ -z "${TARGETS[$arg]:-}" ]]; then
            echo "${R}unknown target: $arg${N} (available: ${ORDER[*]})" >&2
            exit 2
        fi
        SELECTED+=("$arg")
    done
fi

echo "L0 build check"
echo "  logs: $LOG_DIR"
echo
for t in "${SELECTED[@]}"; do
    "${TARGETS[$t]}"
done

echo
echo "======================================================================"
echo "passed: ${#PASSED[@]}   failed: ${#FAILED[@]}   skipped: ${#SKIPPED[@]}"
if [[ ${#SKIPPED[@]} -gt 0 ]]; then
    echo
    echo "${Y}skipped (reduced coverage, not failures):${N}"
    printf '  %s\n' "${SKIPPED[@]}"
fi
if [[ ${#FAILED[@]} -gt 0 ]]; then
    echo
    echo "${R}FAILED: ${FAILED[*]}${N}"
    exit 1
fi
echo
echo "${G}All selected components build.${N}"
